[package]
name = "gol"
version = "0.1.0"
authors = ["Do Duy <juchiast@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3"
hashbrown = "0.2"

[dev-dependencies]
rle = { path = "../rle" }
